### ISSUE TITLE
conda create env trouble

### ISSUE THREAD

**Issue by Mr-firework** [r00tman/EventNeRF#3] opened 2023-05-02 03:21 UTC
This is a awesome work! But I meet some trouble that I can't resolve. 

> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - ipython==7.30.0=py39hf3d152e_0
>

**Comment by SharineLee** [comment] 2023-06-24 15:35
I have the same problem. Do you solve it?

**Comment by SharineLee** [comment] 2023-06-24 15:35
> This is a awesome work! But I meet some trouble that I can't resolve.
> 
> > Collecting package metadata (repodata.json): done
> > Solving environment: failed
> > ResolvePackageNotFound:
> > 
> > * ipython==7.30.0=py39hf3d152e_0

I have the same problem. Do you solve it?

**Comment by Qinghongye** [comment] 2023-10-13 00:50
the problem is still there...

**Comment by Qinghongye** [comment] 2023-10-17 09:51
I have gone to the channel websites and there is no ipython == 7.30.0 but there are some other versions.I dont know whether they will work or not.This is the website"https://conda.anaconda.org/conda-forge/win-64/"

**Comment by r00tman** [comment] 2023-10-23 11:49
Hello, sorry for the delay.

There is no need for ipython, you can remove it from the environment.yml

Also, please try [this updated environment](https://github.com/r00tman/EventNeRF/files/13069643/environment.txt) instead (rename to `environment.yml`).

I removed irrelevant things from it and relaxed version requirements.
Now it installs fine on a clean miniconda3+mamba (through `mamba env create --file environment.yml`)

**Comment by Qinghongye** [comment] 2023-10-23 12:08
Thank you so much man!
Have a good day!

**Comment by r00tman** [comment] 2023-10-23 13:12
Hi! Please also remove "- pymarchingcubes" line from the file before running. There is no way to install it properly through conda, it will fail. You would need to install it through [official instructions](https://github.com/JustusThies/PyMarchingCubes) after everything else is done, in case you need mesh extraction. Otherwise, the code should work fine without the package

**Comment by Mr-firework** [comment] 2023-10-31 10:56
name: eventnerf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.1.2=py39h06a4308_0
  - python=3.9.16=h955ad1f_3
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - configargparse==1.5.5
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.40.0
      - imageio==2.31.1
      - importlib-resources==5.12.0
      - kiwisolver==1.4.4
      - llvmlite==0.38.1
      - matplotlib==3.7.1
      - numba==0.55.1
      - numpy==1.21.6
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pillow==9.5.0
      - protobuf==4.23.3
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - six==1.16.0
      - tensorboardx==2.6.1
      - torch==1.10.0+cu111
      - torchaudio==0.10.0+rocm4.1
      - torchvision==0.11.0+cu111
      - tqdm==4.65.0
      - typing-extensions==4.7.0
      - zipp==3.15.0

**Comment by Mr-firework** [comment] 2023-10-31 10:56
name: eventnerf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.1.2=py39h06a4308_0
  - python=3.9.16=h955ad1f_3
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - configargparse==1.5.5
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.40.0
      - imageio==2.31.1
      - importlib-resources==5.12.0
      - kiwisolver==1.4.4
      - llvmlite==0.38.1
      - matplotlib==3.7.1
      - numba==0.55.1
      - numpy==1.21.6
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pillow==9.5.0
      - protobuf==4.23.3
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - six==1.16.0
      - tensorboardx==2.6.1
      - torch==1.10.0+cu111
      - torchaudio==0.10.0+rocm4.1
      - torchvision==0.11.0+cu111
      - tqdm==4.65.0
      - typing-extensions==4.7.0
      - zipp==3.15.0

**Comment by r00tman** [comment] 2024-03-06 16:38
Hello, is there something still wrong? Or can I close the issue?

**Closed as completed** 2024-03-06 16:45 UTC
